#!/usr/bin/env perl
use strict;
use warnings;
use Github::Tools::Common;
use Data::Dump;
use Carp;
use Try::Tiny;
use Text::SimpleTable::AutoWidth;
use Scalar::Util;
use YAML::XS qw/DumpFile LoadFile/;

use feature ':5.10';


my $name = $ARGV[0] or die "No name given, cannot create";

say "creating: $name";

add_org_repo(org => config 'org', data => {
        name => $name,
        private => 1,
        has_issues => 0,
        has_wiki => 0,
    }) &&
say "  setting hooks" && system("./hooks $name") == 0 &&
say "  fixing grants" && system("./fix-grants $name") == 0 &&

say "repo creation done!";
