#!/usr/bin/env perl
use strict;
use warnings;
use GitHub::Tools::Common;
use Data::Dump;
use Carp;
use Net::HTTP::Spore;
use Try::Tiny;
use Text::SimpleTable::AutoWidth;
use Data::Dump;
use feature ':5.10';

my %skip = (
    'candidate-code' => 1,
    'apdm-candidate-code' => 1,
);
my $g = api();

# Lets add all repos to Employees tema
my $TEAMS = [shift || qw(Employees Bots)];
foreach my $TN (@$TEAMS) {
    my $teams = $g->get_organization_teams(format => 'json', org => 'startsiden')->body;
    my ($team) = grep { $_->{name} eq $TN } @{ $teams->{teams} };

    die "no such team $TN found (found: "
    . join(", ", map { $_->{name} } @{ $teams->{teams} })
    . ")\n" unless $team;
    say "team: " . $team->{id} . " -- " . $team->{name};

    $team->{repos} = $g->get_team_repositories(format => 'json', team => $team->{id})->body;
    my $repos = $g->get_organization_repositories(format => 'json', org => 'startsiden')->body;

    foreach my $r ( @{ $repos->{repositories} } ) {
        next if (grep { $r->{name} eq $_->{name} } @{ $team->{repos}->{repositories} });
        next if ($skip{$r->{name}});
        say $r->{name};

        say "   adding";
        my $res = $g->add_team_repo(format => 'json', team => $team->{id},
            payload => {
                name => $r->{organization} . '/' . $r->{name},
            }
        )->body;
        say dd $res if $ENV{SPORE_TRACE};
    }
}
