#!/usr/bin/env perl
use strict;
use warnings;
use GitHub::Tools::Common;
use Data::Dump;
use Carp;
use Net::HTTP::Spore;
use Try::Tiny;
use Text::SimpleTable::AutoWidth;

use feature ':5.10';
my $table = Text::SimpleTable::AutoWidth->new();
my $hooks = config 'hooks';

$table->captions(['Repo', keys %$hooks ]);
our $add = 0;
if ($ARGV[0]) {
    $add = 1;
}
my $repos;
my $g = api();

if ($ARGV[1]) {
    say "Only checking one repo: " . $ARGV[1];
    push( @$repos, { name => $ARGV[1] } );
} else {
    $repos = $g->list_org_repos(org => 'startsiden')->body;
}

my $i = 0;

foreach my $r (sort { $a->{name} cmp $b->{name} } @$repos) {
    my @row = ($r->{name});
    next if $r->{name} eq 'sandbox';

    say "REPO: " . $r->{name};
    my @res = check_repo_hooks($g, $r, $hooks);
    foreach (@res) {
        if ($_ == 1) {
            push(@row, 'X');
        } elsif ($_ == 2) {
            push(@row, '+');
        } else {
            push(@row, ' ');
        }
    }

    $table->row(@row);
    #last if $i++ > 1;
}

say $table->draw();

sub check_repo_hooks {
    my ($api, $repo, $hooks) = @_;
    my @res;
    # Fetch the content first!
    my $repo_hooks = $g->list_repo_hooks(user => 'startsiden', repo => $repo->{name})->body;


    foreach (values(%$hooks)) {
        #say " $_";
        # Check if we have this one
        my $seen;
        foreach my $h (@$repo_hooks) {
            next unless ($h->{name} eq 'web'); # We only look at web hooks for now
            #say "    " . $h->{config}->{url};
            if ($h->{config}->{url} =~ qr/$_/) {
                $seen = 1;
                # now lets check for repo name
                unless ($h->{config}->{url} =~ qr/$repo->{name}/) {
                    # Need to update this one.
                    say "      Adding repo name!";
                    $g->update_repo_hook(user => 'startsiden', repo => $repo->{name},
                        id => $h->{id},
                        spore_payload => {
                            name => 'web',
                            config => {
                                %{ $h->{config} },
                                url => $h->{config}->{url} . "?x-repo=" . $repo->{name}
                            },
                        }
                    );
                }
                last;
            }
        }
        unless ($seen) {
            # Need to add a hook then!
            say "    Adding hook!";
            $g->add_repo_hook(user => 'startsiden', repo => $repo->{name},
                spore_payload => {
                    name => 'web',
                    config => {
                        url => $_ . "?x-repo=" . $repo->{name},
                    }
                }
            );
            $seen = 2;
        }
        push(@res, $seen);
    }
    return @res;
}
