#!/usr/bin/env perl
use strict; use warnings;
use feature qw(say);
use GitHub::Tools::Common;

iterate_repos(config 'org', sub {
        my $r = shift;
        say "* " . $r->{name} . " - " . $r->{fork};
    }
);
